version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mywardrobe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
volumes:
  postgres_data:
